### PR TITLE
fix: header in const request bug and improve code architecture

### LINKED ISSUE #323: [BUG] Custom headers not sent when const=False
**Description**

Custom header is only sent when const=True
**Expected Behavior**

Custom header must always be sent even without const=True

**Environment:**
- Host OS: Debian GNU/Linux bookworm/sid x86_64 Kernel 6.0.0-2-amd64
- Browser:  Chrome 107.0.5304.110

---

[Optional] **Additional Context**

When using const=False no Custom headers are sent.
```python
app.add_header("Server", "Robyn")
app.add_header("Content-Type", "text/plain")
```

```python
@app.get('/plaintext')
def plaintext() -> str:
    return "Hello, world!"
```
When using const=True Date headers are sent.
```python
@app.get('/plaintext', const=True)
def plaintext() -> str:
    return "Hello, world!"
    
```
I just find this, when trying to run TechEmPower Benchmarks without const

---

### PR DESCRIPTION
**Pull request by AntoineRR**
**Description**

This PR fixes  #323

This is my suggestion for fixing the issue as well as improving the request handling
- Add a `Response` struct created from the hashmap returned by the python functions in `execute_http_request`. I would have liked to return a `Response` directly from the py function by mapping the Rust struct to a Python TypedDict but I'm not sure if it is doable? Maybe consider it for a later PR.
- Remove the `request_handler` module (which became obsolete with the previous point)
- Fix the bug by applying global and request headers to the response before routing on the correct function
- Add a unit test for the headers in const requests

### CODE REVIEW

File: src/executors/mod.rs [hunk 1]
```diff
@@ -1,7 +1,7 @@
 /// This is the module that has all the executor functions
 /// i.e. the functions that have the responsibility of parsing and executing functions.
-use crate::io_helpers::read_file;
 use crate::types::Request;
```
Comment (sansyrox) [inline src/executors/mod.rs:3]: I think importing `use crates::types::{Request, Response}` would make more sense. Just a nit

Comment (AntoineRR) [reply src/executors/mod.rs]: Yes, far better. Autoimport does some weird things sometimes

File: src/io_helpers/mod.rs [hunk 2]
```diff
@@ -4,16 +4,30 @@ use std::io::Read;
...
+#[inline]
+pub fn apply_dashmap_headers(
+    response: &mut HttpResponseBuilder,
+    headers: &DashMap<String, String>,
+) {
+    for h in headers.iter() {
+        response.insert_header((h.key().clone(), h.value().clone()));
+    }
+}
+
```
Comment (sansyrox) [inline src/io_helpers/mod.rs:30]: This is very smart! Good job! 👍

Comment (AntoineRR) [reply src/io_helpers/mod.rs:30]: Thanks ;) This avoids merging the headers and then applying them, which creates an unnecessary copy of both headers list. I wanted to make only one function that works with either a hashmap or a dashmap but it doesn't seem to be easy

File: src/server.rs [hunk 3]
```diff
@@ -308,21 +306,29 @@ impl Default for Server {
...
-async fn merge_headers(
-    global_headers: &Arc<Headers>,
-    request_headers: &HeaderMap,
-) -> HashMap<String, String> {
-    let mut headers = HashMap::new();
+async fn apply_middleware(
+    request: &mut Request,
+    middleware_type: MiddlewareRoute,
+    middleware_router: &MiddlewareRouter,
+    route_uri: &str,
```
Comment (sansyrox) [inline src/server.rs:313]: @AntoineRR , can you please explain this function a bit?

Comment (AntoineRR) [reply src/server.rs:313]: Sure!
We have two middlewares to apply, one before routing and another after it.
We first route on the middleware function and execute it, which gives us some modifications to apply to the `request` object. We only care about the headers for now => they become the request headers.
Therefore the middleware could modify the request (at least the "before" middleware for Robyn currently), which is why `request` is `&mut`.
For the "after" middleware, I think it cannot currently modify the request or the response, so the `execute_midlleware_function` should return an empty hashmap and we will just have executed the python function.
The idea here is just to factorize the code to execute both middlewares so it is easier to understand and maintain. Although if you think it makes sense to keep the execution of both middleware separate it is also possible

Comment (sansyrox) [reply src/server.rs:313]: Perfect. @AntoineRR do you think we can modify request body in `before_request` and response body in `after_request`?

Comment (AntoineRR) [reply src/server.rs:313]: I think it would make sense yes. Maybe introducing a common trait for `Request` and `Response` could help us with this. The `apply_middleware` method would become generic and take either a `Request` or a `Response`, and the trait will then provide a method for parsing the hashmap returned by `execute_middleware_function` and apply it to the object.

Comment (AntoineRR) [reply src/server.rs:313]: I could try to do this in an other PR, as it will add a new feature for Robyn, i.e. response modification in "after" middleware. What do you think of it?

Comment (sansyrox) [reply src/server.rs:313]: > I could try to do this in an other PR, as it will add a new feature for Robyn, i.e. response modification in "after" middleware. What do you think of it?

Sounds great. We implemented some of it here too: https://github.com/sansyrox/robyn/pull/297

Just in case you need any reference.


> Maybe introducing a common trait for Request and Response could help us with this

What kind of trait will it be?

Comment (AntoineRR) [reply src/server.rs:313]: Thanks for the reference :)
This could be something like this I guess:
```
trait Data {
     fn modify_from_hashmap(&mut self, modifications: Hashmap<String, String>) -> &mut self;
}
```
and then `apply_middleware` signature would become:
```
async fn apply_middleware<T: Data>(
    data: &mut T,
    middleware_type: MiddlewareRoute,
    middleware_router: &MiddlewareRouter,
    route_uri: &str,
)
```
After writing impl of `Data` for `Request` and `Response`, they could be used as the `data` parameter for the function. Then we call `data.modify_from_hashmap` with the hashmap from `execute_middleware_function` and we're good! Using generics in Rust is a zero cost abstraction due to monomorphization so there will be no performance impact from this. Using this solution makes modifying requests and response from a hashmap easier IMO, and everything is contained inside the `Request` and `Response` struct.
I don't like the name `Data` for the trait but it is just an example here.

Comment (sansyrox) [reply src/server.rs:313]: > Using generics in Rust is a zero cost abstraction due to monomorphization so there will be no performance impact from this.

I wasn't aware of this. Thank you! 😄

**Review by sansyrox — APPROVED** [review]
Looks great! ❇️ 🔥
